# Use the NVIDIA CUDA base image with a specific CUDA version
FROM nvidia/cuda:12.5.0-devel-ubuntu22.04

LABEL maintainer="ahuertas"

# Set the shell to use bash
SHELL [ "/bin/bash", "--login", "-c" ]

# Update and install basic dependencies
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 unzip zip curl git net-tools zsh fish tree htop build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Node.js from NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN apt-get install ffmpeg libsm6 libxext6  -y

# Environmental variables for wandb
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Create a non-root user with build arguments
ARG username=nonroot
ARG uid=1000
ARG gid=1000

ENV USER $username
ENV UID $uid
ENV GID $gid
ENV HOME /home/$USER

RUN addgroup --gid $GID $USER && \
    adduser --disabled-password --gecos "Non-root user" --uid $UID --gid $GID --home $HOME $USER

USER $USER

# Add the JupyterLab settings
COPY --chown=$uid:$gid compose/.jupyter $HOME/.jupyter

# Install Miniconda
ENV MINICONDA_VERSION 4.10.3
ENV CONDA_DIR $HOME/miniconda3
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_$MINICONDA_VERSION-Linux-x86_64.sh -O ~/miniconda.sh && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh

ENV PATH=$CONDA_DIR/bin:$PATH

RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile
RUN conda init bash

ENV PROJECT_DIR $HOME
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR

RUN mkdir -p /home/$USER/work && chown -R $USER:$GID /home/$USER/work

ENV ENV_PREFIX $PROJECT_DIR/env
RUN conda install --name base --channel conda-forge mamba
RUN mamba update --name base --channel defaults conda

COPY --chown=$UID:$GID compose/environment.yml compose/requirements.txt ./
RUN mamba env create --prefix $ENV_PREFIX --file environment.yml
RUN conda clean --all --yes

COPY --chown=$UID:$GID compose/postBuild /usr/local/bin
RUN chmod u+x /usr/local/bin/postBuild
RUN conda activate $ENV_PREFIX && /usr/local/bin/postBuild && conda deactivate

COPY --chown=$UID:$GID compose/entrypoint.sh /usr/local/bin
RUN chmod u+x /usr/local/bin/entrypoint.sh
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

RUN echo "conda activate $ENV_PREFIX" >> ~/.bashrc

# # Set environment variables for CUDA
# autokeras info: https://github.com/keras-team/autokeras/issues/1813
# ENV PATH /usr/local/cuda-12.5/bin:${PATH}
# ENV LD_LIBRARY_PATH /usr/local/cuda-12.5/lib64:${LD_LIBRARY_PATH}
# ENV CUDA_HOME /usr/local/cuda-12.5

# # Debug: List the contents of the CUDA directory to verify the file's existence
# RUN ls -l /usr/local/cuda-12.5 
# # /nvvm/libdevice/

# # Copy the libdevice to the expected location
# RUN cp /usr/local/cuda-12.5/nvvm/libdevice/libdevice.10.bc /usr/local/cuda-12.5/lib64/

# # Optional: Set additional environment variables if necessary
# ENV TF_CUDA_PATHS /usr/local/cuda-12.5:/usr/local/cuda
# ENV NVVMIR_LIBRARY_DIR /usr/local/cuda-12.5/nvvm/libdevice

# Default command to run JupyterLab
ARG jupyter_token
ENV jupyter_token=${jupyter_token}
CMD [ "/bin/bash", "-c", "jupyter lab --no-browser --ip 0.0.0.0 --allow-root --ContentsManager.allow_hidden=True --NotebookApp.token=$jupyter_token"]
